### ISSUE TITLE
於 LibreOffice 底下創用 CC 授權條款圖示顯示不正常

### ISSUE THREAD

**Issue by Vdragon** [Vdragon/ubuntu-dual-boot#2]
## 問題描述

![20140727_003](https://cloud.githubusercontent.com/assets/1192163/3713532/e888771e-1571-11e4-9b2e-7a569db4e580.jpg)
<del>似乎原始版本就已經有這個問題</del>原始版本的 PDF 並沒有這個問題，目前懷疑是 LibreOffice 自己的 bug 導致的
## 上游軟體問題追蹤系統回報

https://www.libreoffice.org/bugzilla/show_bug.cgi?id=82342

**Comment by Explorer09** [comment]
我不知道要怎麼report這個問題到上游。因為當我使用Ubuntu 14.04內附的LibreOffice (4.2.3~rc3-0ubuntu2) 顯示會正常，反而是改用 ppa:libreoffice/ppa 的時候才會出現這狀況。
剛剛測試 trusty-updates 來源的版本 (4.2.4-0ubuntu2) 也有此問題(不正常)。Windows版尚未測試。

**Comment by Explorer09** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2487263/3713831/c271f8ec-1586-11e4-8691-606b0a4424ee.png)
Windows 版 LibreOffice (4.2.5.2) 顯示不正常，看來是上游的bug了

**Comment by Vdragon** [comment]
我來回報吧，感謝提供資訊

**Comment by Explorer09** [comment]
已在上游回報
https://www.libreoffice.org/bugzilla/show_bug.cgi?id=82342

**Comment by Vdragon** [comment]
感謝XDD

2014-08-08 17:25 GMT+08:00 Kang-Che Sung (宋岡哲) notifications@github.com:

**Comment by Vdragon** [comment]
根據上游問題報告於 4.3.1 已修復，確認中……

**Comment by Vdragon** [comment]
4.3.1.1 圖片顯示正常
